<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FraudRuleEngine.Application\FraudRuleEngine.Application.csproj" />
    <ProjectReference Include="..\FraudRuleEngine.Infrastructure\FraudRuleEngine.Infrastructure.csproj" />
  </ItemGroup>

</Project>
