// <auto-generated />
using System;
using FraudRuleEngine.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FraudRuleEngine.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(FraudEngineDbContext))]
    partial class FraudEngineDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FraudRuleEngine.Infrastructure.Persistence.StoredAssessment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("customer_id");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("decision");

                    b.Property<DateTimeOffset>("EvaluatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("evaluated_at_utc");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("event_id");

                    b.Property<int>("RiskScore")
                        .HasColumnType("integer")
                        .HasColumnName("risk_score");

                    b.Property<string>("RuleSetVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("rule_set_version");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("transaction_id");

                    b.HasKey("Id")
                        .HasName("pk_fraud_assessments");

                    b.HasIndex("EventId")
                        .IsUnique()
                        .HasDatabaseName("ux_fraud_assessments_event_id");

                    b.HasIndex("CustomerId", "EvaluatedAtUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_fraud_assessments_customer_evaluated_at");

                    b.HasIndex("EvaluatedAtUtc", "Id")
                        .IsDescending()
                        .HasDatabaseName("ix_fraud_assessments_evaluated_at_id");

                    b.HasIndex("Decision", "EvaluatedAtUtc", "Id")
                        .IsDescending(false, true, true)
                        .HasDatabaseName("ix_fraud_assessments_decision_evaluated_at_id");

                    b.ToTable("fraud_assessments", (string)null);
                });

            modelBuilder.Entity("FraudRuleEngine.Infrastructure.Persistence.StoredRuleOutcome", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("AssessmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("assessment_id");

                    b.Property<bool>("IsTriggered")
                        .HasColumnType("boolean")
                        .HasColumnName("is_triggered");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer")
                        .HasColumnName("ordinal");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("reason");

                    b.Property<string>("RuleId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("rule_id");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("severity");

                    b.HasKey("Id")
                        .HasName("pk_rule_outcomes");

                    b.HasIndex("AssessmentId")
                        .HasDatabaseName("ix_rule_outcomes_assessment_id");

                    b.HasIndex("RuleId")
                        .HasDatabaseName("ix_rule_outcomes_rule_id_triggered")
                        .HasFilter("is_triggered = true");

                    b.ToTable("rule_outcomes", (string)null);
                });

            modelBuilder.Entity("FraudRuleEngine.Infrastructure.Persistence.StoredTransaction", b =>
                {
                    b.Property<string>("EventId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("event_id");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("account_id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("amount");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("category");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("channel");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("country_code");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("customer_id");

                    b.Property<DateTimeOffset>("IngestedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ingested_at_utc");

                    b.Property<string>("MerchantId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("merchant_id");

                    b.Property<string>("MerchantName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("merchant_name");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<int>("OffsetMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("offset_minutes");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("transaction_id");

                    b.HasKey("EventId")
                        .HasName("pk_transaction_events");

                    b.HasIndex("TransactionId")
                        .HasDatabaseName("ix_transaction_events_transaction_id");

                    b.HasIndex("CustomerId", "OccurredAtUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_transaction_events_customer_occurred_at");

                    b.ToTable("transaction_events", (string)null);
                });

            modelBuilder.Entity("FraudRuleEngine.Infrastructure.Persistence.StoredAssessment", b =>
                {
                    b.HasOne("FraudRuleEngine.Infrastructure.Persistence.StoredTransaction", null)
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_fraud_assessments_transaction_events_event_id");
                });

            modelBuilder.Entity("FraudRuleEngine.Infrastructure.Persistence.StoredRuleOutcome", b =>
                {
                    b.HasOne("FraudRuleEngine.Infrastructure.Persistence.StoredAssessment", null)
                        .WithMany("RuleOutcomes")
                        .HasForeignKey("AssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_rule_outcomes_fraud_assessments_assessment_id");
                });

            modelBuilder.Entity("FraudRuleEngine.Infrastructure.Persistence.StoredAssessment", b =>
                {
                    b.Navigation("RuleOutcomes");
                });
#pragma warning restore 612, 618
        }
    }
}
